### PR TITLE
GH Actions file for Linux Build

### PR DESCRIPTION
**Pull request by kphanipavan**
Added GH actions workflow file for:
1. Make linux build on the latest commit
2. Package it into an AppImage
3. Publish it in releases section

on every commit.

### CODE REVIEW

**Comment by gumbarros** [comment]
Awesome idea @kphanipavan !
The LinuxAppImage pipeline is not working because there is no release tag in this repo right?
```
  Attempting to create or update release tag "latest"
  Could not create new tag "refs/tags/latest" (Resource not accessible by integration) therefore updating existing tag "tags/latest"
  Error: Resource not accessible by integration
  (node:5271) UnhandledPromiseRejectionWarning: HttpError: Resource not accessible by integration
```

**Comment by kphanipavan** [comment]
Yes, but it wasn't in my fork either and the action passed successfully and was able to create a beta release...

Screenshot_20221013_205408

My theory is that it failed because the action ran in a PR env, and was unable to publish it in releases section. Not sure though

**Comment by gumbarros** [comment]
Nice, I will accept the PR, I suppose it's because of the PR environment too.

**Comment by gumbarros** [comment]
Just a last question, it will run on every commit on master or every commit in every branch?

**Review by gumbarros — APPROVED** [review]

**Comment by gumbarros** [comment]
I just saw it doing a review, only on the master, congratulations for the work.

**Comment by kphanipavan** [comment]
on push to master and on PR to master, no??
image

**Pull request merged**
